FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install
# script for prisma generation 
RUN npm run db:generate

# Can you filter the build down to just one app?
RUN npm run build

#another script in global package.json to start the paytm client app for docker 
CMD ["npm", "run", "start-paytm-user"]  